export const appointmentList = [
  {
    doctorName: "Dr. J Reed",
    appointments: [
      {
        startTime: "09:00a",
        name: "Book Doctor Mitchener",
        duration: "30min",
        status: "BOOKED",
      },
      {
        startTime: "09:30a",
        name: "Book Doctor Mitchener",
        duration: "30min",
        status: "BOOKED",
      },
      {
        startTime: "10:00a",
        name: "Book Doctor Mitchener",
        duration: "30min",
        status: "BOOKED",
      },
      {
        startTime: "10:30a",
        name: "Book Doctor Mitchener",
        duration: "30min",
        status: "BOOKED",
      },
      {
        startTime: "11:00a",
        name: "Book Doctor Mitchener",
        duration: "30min",
        status: "BOOKED",
      },
      {
        startTime: "11:30a",
        name: "Book Doctor Mitchener",
        duration: "30min",
        status: "BOOKED",
      },
      {
        startTime: "01:30p",
        name: "Book Doctor Mitchener",
        duration: "30min",
        status: "BOOKED",
      },
      {
        startTime: "02:00p",
        name: "Book Doctor Mitchener",
        duration: "30min",
        status: "BOOKED",
      },
      {
        startTime: "02:30p",
        name: "Book Doctor Mitchener",
        duration: "30min",
        status: "BOOKED",
      },
      {
        startTime: "03:00p",
        name: "Book Doctor Mitchener",
        duration: "30min",
        status: "BOOKED",
      },
      {
        startTime: "03:30p",
        name: "Book Doctor Mitchener",
        duration: "30min",
        status: "BOOKED",
      },
      {
        startTime: "04:00p",
        name: "Book Doctor Mitchener",
        duration: "30min",
        status: "BOOKED",
      },
      {
        startTime: "04:30p",
        name: "Book Doctor Mitchener",
        duration: "30min",
        status: "BOOKED",
      },
      {
        startTime: "05:00p",
        name: "Book Doctor Mitchener",
        duration: "30min",
        status: "CANCELLED",
      },
      {
        startTime: "05:30p",
        name: "Book Doctor Mitchener",
        duration: "30min",
        status: "CANCELLED",
      },
      {
        startTime: "06:00p",
        name: "Book Doctor Mitchener",
        duration: "30min",
        status: "CANCELLED",
      },
      {
        startTime: "06:30p",
        name: "Book Doctor Mitchener",
        duration: "30min",
        status: "CANCELLED",
      },
    ],
  },
  {
    doctorName: "Dr. J Ram",
    appointments: [
      {
        startTime: "09:30a",
        name: "Book Doctor Mitchener",
        duration: "30min",
        status: "BOOKED",
      },
      {
        startTime: "10:00a",
        name: "Book Doctor Mitchener",
        duration: "30min",
        status: "CANCELLED",
      },
      {
        startTime: "10:30a",
        name: "Book Doctor Mitchener",
        duration: "30min",
        status: "BOOKED",
      },

      {
        startTime: "11:30a",
        name: "Book Doctor Mitchener",
        duration: "30min",
        status: "BOOKED",
      },
      {
        startTime: "01:30p",
        name: "Book Doctor Mitchener",
        duration: "30min",
        status: "BOOKED",
      },
      {
        startTime: "02:00p",
        name: "Book Doctor Mitchener",
        duration: "30min",
        status: "BOOKED",
      },
      {
        startTime: "02:30p",
        name: "Book Doctor Mitchener",
        duration: "30min",
        status: "BOOKED",
      },
      {
        startTime: "03:00p",
        name: "Book Doctor Mitchener",
        duration: "30min",
        status: "BOOKED",
      },
      {
        startTime: "03:30p",
        name: "Book Doctor Mitchener",
        duration: "30min",
        status: "BOOKED",
      },
      {
        startTime: "04:00p",
        name: "Book Doctor Mitchener",
        duration: "30min",
        status: "BOOKED",
      },
      {
        startTime: "04:30p",
        name: "Book Doctor Mitchener",
        duration: "30min",
        status: "BOOKED",
      },
      {
        startTime: "05:00p",
        name: "Book Doctor Mitchener",
        duration: "30min",
        status: "CANCELLED",
      },
      {
        startTime: "05:30p",
        name: "Book Doctor Mitchener",
        duration: "30min",
        status: "CANCELLED",
      },
      {
        startTime: "06:00p",
        name: "Book Doctor Mitchener",
        duration: "30min",
        status: "CANCELLED",
      },
      {
        startTime: "06:30p",
        name: "Book Doctor Mitchener",
        duration: "30min",
        status: "CANCELLED",
      },
    ],
  },
];
