export const diagnostics = [
  {name: "Medical History"},
  // {name: "Chronological"},
  {name: "Diagnoses"},
  {name: "Diet"},
  {name: "Injections"},
  {name: "Lab"},
  {name: "Prescriptions"},
  {name: "Reminder"},
  {name: "Surgery"},
  {name: "VAACS"},
  {name: "X-Ray"},
  {name: "Soap"},
  {name: "Notes"},
  {name: "Public"},
  {name: "Attachments"},
  {name: "Requisitions"},
  {name: "Plan"},
];
